"""
Stripped CIF Generator - Create minimal CIF files with essential crystallographic data

This module provides functionality to generate "stripped" CIF files that contain only
the fundamental structural information needed for crystallographic analysis, removing
all metadata and additional information required for database deposition.

The stripped CIF contains only:
- Structure name (data_ block)
- Symmetry information (space group, cell setting, Hall symbol)
- Symmetry operators
- Unit cell parameters
- Atomic coordinates with displacement parameters

Classes:
    StrippedCIFGenerator: Main class for generating stripped CIF files
"""

import os
import re
from typing import Dict, List, Optional, Set, Tuple
from pathlib import Path

try:
    from .CIF_parser import CIFParser, CIFField
except ImportError:
    # For standalone testing
    from CIF_parser import CIFParser, CIFField


class StrippedCIFGenerator:
    """
    Generator for creating stripped CIF files containing only essential crystallographic data.
    
    A stripped CIF includes only the fundamental structural information:
    - Data block name
    - Symmetry information
    - Unit cell parameters  
    - Atomic coordinates and displacement parameters
    
    All metadata, experimental details, and publication information are removed.
    """
    
    # Fields to retain in stripped CIF
    ESSENTIAL_FIELDS = {
        # Symmetry information
        '_symmetry_cell_setting',
        '_symmetry_space_group_name_H-M',
        '_symmetry_space_group_name_H_M',  # Alternative format
        '_symmetry_Int_Tables_number',
        '_space_group_name_Hall',
        '_space_group_name_H-M_alt',
        '_space_group_IT_number',
        
        # Symmetry operators (loop)
        '_symmetry_equiv_pos_site_id',
        '_symmetry_equiv_pos_as_xyz',
        '_space_group_symop_operation_xyz',  # Alternative format
        '_space_group_symop_id',
        
        # Unit cell parameters
        '_cell_length_a',
        '_cell_length_b', 
        '_cell_length_c',
        '_cell_angle_alpha',
        '_cell_angle_beta',
        '_cell_angle_gamma',
        '_cell_volume',
        
        # Atomic coordinates (loop)
        '_atom_site_label',
        '_atom_site_type_symbol',
        '_atom_site_fract_x',
        '_atom_site_fract_y',
        '_atom_site_fract_z',
        '_atom_site_U_iso_or_equiv',
        '_atom_site_adp_type',  # Use adp_type instead of thermal_displace_type
    }
    
    def __init__(self):
        """
        Initialize the stripped CIF generator.
        """
        self.parser = CIFParser()
        self._default_header_path = os.path.join(os.path.dirname(__file__), 'default_cif_header.txt')
        self._custom_header_content = None
        self._default_header_content = None
        
        # Load default header
        self._load_default_header()
    
    def _load_default_header(self):
        """Load default header content from file."""
        try:
            if os.path.exists(self._default_header_path):
                with open(self._default_header_path, 'r', encoding='utf-8') as f:
                    self._default_header_content = f.read().strip()
            else:
                # Fallback if default header file doesn't exist
                self._default_header_content = (
                    "# Stripped CIF File\n"
                    "# Contains only essential crystallographic data:\n"
                    "#   - Structure name and space group\n"
                    "#   - Unit cell parameters\n"
                    "#   - Atomic coordinates\n"
                    "# Generated by CIF Checker"
                )
        except Exception as e:
            print(f"Warning: Could not load default header: {e}")
            self._default_header_content = "# Stripped CIF File"
    
    def load_custom_header(self, header_file_path: str) -> bool:
        """
        Load custom header content from file.
        
        Args:
            header_file_path: Path to custom header file
            
        Returns:
            bool: True if header loaded successfully, False otherwise
        """
        try:
            if os.path.exists(header_file_path):
                with open(header_file_path, 'r', encoding='utf-8') as f:
                    self._custom_header_content = f.read().strip()
                return True
            else:
                print(f"Warning: Header file not found: {header_file_path}")
                return False
        except Exception as e:
            print(f"Warning: Could not load custom header file {header_file_path}: {e}")
            return False
    
    def generate_stripped_cif(self, cif_content: str, header_type: str = 'none') -> str:
        """
        Generate a stripped CIF from the input CIF content.
        
        Args:
            cif_content: The original CIF content as a string
            header_type: Type of header to include ('default', 'custom', 'none')
            
        Returns:
            Stripped CIF content as a string
        """
        # Parse the input CIF
        fields = self.parser.parse_file(cif_content)
        
        # Extract data block name
        data_block_name = self._extract_data_block_name(cif_content)
        
        # Filter essential fields
        essential_fields = self._filter_essential_fields(fields)
        
        # Identify and extract loops
        symmetry_loop, atom_site_loop = self._extract_loops(cif_content, essential_fields)
        
        # Generate the stripped CIF content
        stripped_content = self._build_stripped_cif(
            data_block_name, essential_fields, symmetry_loop, atom_site_loop, header_type
        )
        
        return stripped_content
    
    def generate_stripped_cif_from_file(self, input_file_path: str, output_file_path: str, 
                                      header_type: str = 'none') -> bool:
        """
        Generate a stripped CIF from an input file and save to output file.
        
        Args:
            input_file_path: Path to the input CIF file
            output_file_path: Path where the stripped CIF will be saved
            header_type: Type of header to include ('default', 'custom', 'none')
            
        Returns:
            True if successful, False otherwise
        """
        try:
            # Read input file
            with open(input_file_path, 'r', encoding='utf-8') as f:
                cif_content = f.read()
            
            # Generate stripped CIF
            stripped_content = self.generate_stripped_cif(cif_content, header_type)
            
            # Write output file
            with open(output_file_path, 'w', encoding='utf-8') as f:
                f.write(stripped_content)
            
            return True
            
        except Exception as e:
            print(f"Error generating stripped CIF: {e}")
            return False
    
    def _extract_data_block_name(self, cif_content: str) -> str:
        """Extract the data block name from CIF content."""
        lines = cif_content.splitlines()
        for line in lines:
            line = line.strip()
            if line.startswith('data_'):
                return line
        return 'data_stripped'  # Default if not found
    
    def _filter_essential_fields(self, fields: Dict[str, CIFField]) -> Dict[str, CIFField]:
        """Filter fields to keep only essential ones."""
        essential = {}
        for field_name, field in fields.items():
            if field_name.lower() in {f.lower() for f in self.ESSENTIAL_FIELDS}:
                essential[field_name] = field
        return essential
    
    def _extract_loops(self, cif_content: str, essential_fields: Dict[str, CIFField]) -> Tuple[Optional[str], Optional[str]]:
        """
        Extract loop structures for symmetry operations and atomic coordinates.
        
        Args:
            cif_content: Original CIF content
            essential_fields: Dictionary of essential fields
            
        Returns:
            Tuple of (symmetry_loop_content, atom_site_loop_content)
        """
        lines = cif_content.splitlines()
        symmetry_loop = None
        atom_site_loop = None
        
        i = 0
        while i < len(lines):
            line = lines[i].strip()
            
            if line == 'loop_':
                # Extract the complete loop
                loop_content, lines_consumed = self._extract_single_loop(lines, i)
                
                # Determine loop type based on field names
                if self._is_symmetry_loop(loop_content):
                    symmetry_loop = loop_content
                elif self._is_atom_site_loop(loop_content):
                    # Filter atom site loop to only include essential fields
                    atom_site_loop = self._filter_atom_site_loop(loop_content)
                
                i += lines_consumed
            else:
                i += 1
        
        return symmetry_loop, atom_site_loop
    
    def _extract_single_loop(self, lines: List[str], start_index: int) -> Tuple[str, int]:
        """Extract a complete loop structure starting from loop_ keyword."""
        loop_lines = []
        i = start_index
        
        # Add the loop_ line
        loop_lines.append(lines[i])
        i += 1
        
        # Collect field names (lines starting with _)
        while i < len(lines):
            line = lines[i].strip()
            if not line:
                loop_lines.append(lines[i])
                i += 1
                continue
            if line.startswith('_'):
                loop_lines.append(lines[i])
                i += 1
            else:
                break
        
        # Collect data rows
        while i < len(lines):
            line = lines[i].strip()
            
            # Stop if we hit another CIF construct
            if (line.startswith('_') or line.startswith('loop_') or 
                line.startswith('data_') or line.startswith('global_') or 
                line.startswith('save_')):
                break
            
            # Add the data line
            loop_lines.append(lines[i])
            i += 1
        
        return '\n'.join(loop_lines), i - start_index
    
    def _is_symmetry_loop(self, loop_content: str) -> bool:
        """Check if a loop contains symmetry operation fields."""
        symmetry_indicators = [
            '_symmetry_equiv_pos_site_id',
            '_symmetry_equiv_pos_as_xyz',
            '_space_group_symop_operation_xyz',
            '_space_group_symop_id'
        ]
        return any(indicator in loop_content for indicator in symmetry_indicators)
    
    def _is_atom_site_loop(self, loop_content: str) -> bool:
        """Check if a loop contains atomic coordinate fields."""
        # Look for the core atom site fields that define actual atomic coordinates
        core_atom_site_indicators = [
            '_atom_site_label',
            '_atom_site_type_symbol',
            '_atom_site_fract_x',
            '_atom_site_fract_y',
            '_atom_site_fract_z'
        ]
        
        # Must have at least 3 of the core fields to be considered an atom site loop
        matches = sum(1 for indicator in core_atom_site_indicators if indicator in loop_content)
        
        # Also exclude restraint loops which may contain atom_site in field names
        restraint_indicators = [
            '_restr_',
            '_restraint_',
            '_RIGU_',
            '_DELU_',
            '_SIMU_',
            '_DFIX_'
        ]
        
        # If it looks like a restraint loop, it's not an atom site loop
        if any(indicator in loop_content for indicator in restraint_indicators):
            return False
            
        return matches >= 3
    
    def _filter_atom_site_loop(self, loop_content: str) -> str:
        """Filter atom site loop to include only essential fields in the correct order."""
        lines = loop_content.splitlines()
        
        # Essential atom site fields in the desired order
        essential_atom_fields = [
            '_atom_site_label',
            '_atom_site_type_symbol',
            '_atom_site_fract_x',
            '_atom_site_fract_y',
            '_atom_site_fract_z',
            '_atom_site_U_iso_or_equiv',
            '_atom_site_adp_type'
        ]
        
        # Alternative field names that should be mapped to essential fields
        field_aliases = {
            '_atom_site_thermal_displace_type': '_atom_site_adp_type'
        }
        
        # Find the start of field definitions (after loop_)
        field_start = 1  # Skip the 'loop_' line
        
        # Collect all field names and their positions
        original_fields = []
        field_positions = {}
        
        i = field_start
        while i < len(lines):
            line = lines[i].strip()
            if not line:
                i += 1
                continue
            if line.startswith('_'):
                original_fields.append(line)
                field_positions[line.lower()] = len(original_fields) - 1
                i += 1
            else:
                break
        
        # Start of data rows
        data_start = i
        
        # Build filtered loop
        filtered_lines = ['loop_']
        
        # Add only essential fields that exist in the original loop
        present_essential_fields = []
        for field in essential_atom_fields:
            field_lower = field.lower()
            if field_lower in field_positions:
                filtered_lines.append(field)
                present_essential_fields.append((field, field_lower))
            else:
                # Check for aliases
                for alias, target in field_aliases.items():
                    if target.lower() == field_lower and alias.lower() in field_positions:
                        filtered_lines.append(field)  # Use the standard name
                        present_essential_fields.append((field, alias.lower()))
                        break
        
        # If no essential fields found, return the original loop content
        if not present_essential_fields:
            return loop_content
        
        # Process data rows
        for i in range(data_start, len(lines)):
            line = lines[i].strip()
            if not line:
                continue
            
            # Parse data row - handle quoted values properly
            data_values = []
            in_quotes = False
            current_value = ""
            quote_char = None
            
            j = 0
            while j < len(line):
                char = line[j]
                if not in_quotes:
                    if char in ("'", '"'):
                        in_quotes = True
                        quote_char = char
                        current_value = ""
                    elif char.isspace():
                        if current_value:
                            data_values.append(current_value)
                            current_value = ""
                    else:
                        current_value += char
                else:
                    if char == quote_char:
                        in_quotes = False
                        data_values.append(current_value)
                        current_value = ""
                        quote_char = None
                    else:
                        current_value += char
                j += 1
            
            # Add the last value if there is one
            if current_value:
                data_values.append(current_value)
            
            if len(data_values) >= len(present_essential_fields):
                # Extract only values for essential fields
                filtered_values = []
                for field_name, lookup_name in present_essential_fields:
                    field_pos = field_positions[lookup_name]
                    if field_pos < len(data_values):
                        filtered_values.append(data_values[field_pos])
                
                if filtered_values:
                    filtered_lines.append(' '.join(filtered_values))
        
        return '\n'.join(filtered_lines)
    
    def _build_stripped_cif(self, data_block_name: str, essential_fields: Dict[str, CIFField],
                           symmetry_loop: Optional[str], atom_site_loop: Optional[str],
                           header_type: str) -> str:
        """Build the final stripped CIF content."""
        lines = []
        
        # Add header based on type
        if header_type == 'default' and self._default_header_content:
            lines.append(self._default_header_content)
            lines.append('')
        elif header_type == 'custom' and self._custom_header_content:
            lines.append(self._custom_header_content)
            lines.append('')
        # No header for 'none' type
        
        # Add data block name
        lines.append(data_block_name)
        lines.append('')
        
        # Add symmetry information (non-loop fields)
        symmetry_fields = self._get_symmetry_fields(essential_fields)
        if symmetry_fields:
            for field_name, field in symmetry_fields.items():
                lines.extend(self._format_field(field))
            lines.append('')
        
        # Add symmetry operations loop
        if symmetry_loop:
            lines.append(symmetry_loop.strip())
            lines.append('')
        
        # Add unit cell parameters
        cell_fields = self._get_cell_fields(essential_fields)
        if cell_fields:
            for field_name, field in cell_fields.items():
                lines.extend(self._format_field(field))
            lines.append('')
        
        # Add atomic coordinates loop
        if atom_site_loop:
            lines.append(atom_site_loop.strip())
            lines.append('')
        
        # Add END marker
        lines.append('#END')
        
        return '\n'.join(lines).strip() + '\n'
    
    def _get_symmetry_fields(self, essential_fields: Dict[str, CIFField]) -> Dict[str, CIFField]:
        """Get symmetry-related fields (excluding loop fields)."""
        symmetry_field_names = {
            '_symmetry_cell_setting',
            '_symmetry_space_group_name_H-M',
            '_symmetry_space_group_name_H_M',
            '_symmetry_Int_Tables_number',
            '_space_group_name_Hall',
            '_space_group_name_H-M_alt',
            '_space_group_IT_number'
        }
        
        return {name: field for name, field in essential_fields.items() 
                if name.lower() in {f.lower() for f in symmetry_field_names}}
    
    def _get_cell_fields(self, essential_fields: Dict[str, CIFField]) -> Dict[str, CIFField]:
        """Get unit cell parameter fields."""
        cell_field_names = {
            '_cell_length_a',
            '_cell_length_b',
            '_cell_length_c',
            '_cell_angle_alpha',
            '_cell_angle_beta',
            '_cell_angle_gamma',
            '_cell_volume'
        }
        
        return {name: field for name, field in essential_fields.items()
                if name.lower() in {f.lower() for f in cell_field_names}}
    
    def _format_field(self, field: CIFField) -> List[str]:
        """Format a single field for output."""
        if field.value is None:
            return [field.name]
        
        # Check if we need multiline format
        if field.is_multiline or '\n' in str(field.value):
            return [field.name, ';', str(field.value), ';']
        else:
            # Single line format
            value = str(field.value)
            # Add quotes if needed
            if (' ' in value or value.startswith(';') or value.startswith('#') or
                value.startswith("'") or value.startswith('"')):
                value = f"'{value}'"
            
            return [f"{field.name}    {value}"]
    
    def get_essential_fields_list(self) -> List[str]:
        """Get a list of all essential field names that are retained in stripped CIFs."""
        return sorted(list(self.ESSENTIAL_FIELDS))
    
    def validate_cif_for_stripping(self, cif_content: str) -> Dict[str, any]:
        """
        Validate if a CIF contains sufficient information for creating a meaningful stripped version.
        
        Args:
            cif_content: The CIF content to validate
            
        Returns:
            Dictionary with validation results including missing critical fields
        """
        fields = self.parser.parse_file(cif_content)
        
        # Critical fields that should be present
        critical_fields = {
            '_cell_length_a', '_cell_length_b', '_cell_length_c',
            '_atom_site_label', '_atom_site_fract_x', '_atom_site_fract_y', '_atom_site_fract_z'
        }
        
        present_fields = set(fields.keys())
        missing_critical = critical_fields - {f.lower() for f in present_fields}
        
        # Check for atomic coordinates loop
        has_atom_loop = any('_atom_site_' in field.lower() for field in present_fields)
        
        # Check for symmetry information
        has_symmetry = any('_symmetry_' in field.lower() or '_space_group_' in field.lower() 
                          for field in present_fields)
        
        result = {
            'is_suitable': len(missing_critical) == 0 and has_atom_loop,
            'missing_critical_fields': list(missing_critical),
            'has_atomic_coordinates': has_atom_loop,
            'has_symmetry_info': has_symmetry,
            'total_essential_fields_present': len(self._filter_essential_fields(fields)),
            'recommendations': []
        }
        
        if not has_atom_loop:
            result['recommendations'].append("No atomic coordinates found - stripped CIF will be incomplete")
        if not has_symmetry:
            result['recommendations'].append("No symmetry information found - consider adding space group details")
        if missing_critical:
            result['recommendations'].append(f"Missing critical fields: {', '.join(missing_critical)}")
        
        return result
